### ISSUE TITLE
Split into multiple requireables

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-express#15]
This is super low urgency (right now this module is pretty neat and small) but want to document what (in my opinion) what preventative measures we should take to stop this turning into a big ugly monolith and dumping ground for any helper that needs to span more than one application.

```js
require('ft-next-express');  // => full fat ft-next-express as it is now
require('ft-next-express/default'); // => an alias to that ^
```
```js
require('ft-next-express/simple'); // => everything except templating, static assets & helpers
```

```js
require('ft-next-express/helpers'); // => just an object containing the default handlebars helpers
```

```js
require('ft-next-express/static'); // => middleware for setting up next standard static assets
```

Where:
- **default** is the same as it is now for backwards compatibility
- **simple** is intended for APIs or for people want to use other templating libraries
- **helpers** just the helpers
- **static** effectively [this](https://github.com/Financial-Times/next-express/blob/master/main.js#L45-50) middleware

Perhaps some of these even to be moved out into their own repositories eventually.

**Comment by wheresrhys** [comment]
Or how about something like

```js

var app = require('next-express')
   .withCapi()
   .withFastFT()
   .withHandlebars()

```

**Comment by matthew-andrews** [comment]
Hmm not seeing the benefit of this…

Seems to me this just adds complexity and restrictions …  Not obvious how you'd get the handlebars config and use it on is own, for example …

Also that would be a breaking API change, which can be avoided by just splitting into different files …

**Comment by wheresrhys** [comment]
The attraction of it for me - other than I like it as an API - is that it avoids having to make a decision about what 'simple' means, and in general avoids having to make too many decisions about what constitutes a useful bundle and what that bundle should be called. Each feature would have a chainable method and products build their own bundle of express add-ons which I think is less restrictive. 

We could still define some god-methods e.g. `.withEverything()`, `.forApis()`, for easy one step setup. The underlying code could still be structured how you propose so 'get the handlebars config and use it on is own' would still be possible (although if that's something we care about then arguably it should go into its own module sooner rather than later anyway... and in general I don't like `require('module/file')`)

You're right... it would be a breaking change, which is annoying, but that's what semver's for

Another thing that just occurred to me; as features get added (even if/when they get extracted to dependencies) we still have a growth in dependencies... so *every* consumer of next-express gets handlebars, fastft-api-client etc... Is it worth considering a plugin architecture? Or an inverted version of your approach e.g. app consumes next-website, which consumes next-express-simple + next-handlebars, api consumes next-api which consumes next-express-simple.

**Comment by matthew-andrews** [comment]
feels like this dep isn't ballooning in complexity. closing for now
